# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vector_join <- function(v, token) {
    .Call('mango_vector_join', PACKAGE = 'mango', v, token)
}

string_split <- function(s, delimiter) {
    .Call('mango_string_split', PACKAGE = 'mango', s, delimiter)
}

parseFastq <- function(fastq1, fastq2, basename, minlength = 15L, maxlength = 25L, keepempty = FALSE, verbose = TRUE, linker1 = "GTTGGATAAG", linker2 = "GTTGGAATGT") {
    .Call('mango_parseFastq', PACKAGE = 'mango', fastq1, fastq2, basename, minlength, maxlength, keepempty, verbose, linker1, linker2)
}

buildBedpe <- function(sam1, sam2, bedpefile) {
    invisible(.Call('mango_buildBedpe', PACKAGE = 'mango', sam1, sam2, bedpefile))
}

removeDupBedpe <- function(infile, outfile) {
    invisible(.Call('mango_removeDupBedpe', PACKAGE = 'mango', infile, outfile))
}

splitBedbyChrom <- function(bedfile, outnamebase) {
    .Call('mango_splitBedbyChrom', PACKAGE = 'mango', bedfile, outnamebase)
}

splitBedpe <- function(bedpein, outnamebase, printreads = TRUE, printpets = TRUE) {
    .Call('mango_splitBedpe', PACKAGE = 'mango', bedpein, outnamebase, printreads, printpets)
}

buildTagAlign <- function(bedpefile, TagAlignfile) {
    invisible(.Call('mango_buildTagAlign', PACKAGE = 'mango', bedpefile, TagAlignfile))
}

external_sort <- function(inputfile, outputfile) {
    invisible(.Call('mango_external_sort', PACKAGE = 'mango', inputfile, outputfile))
}

